name: AutoGPT Ubuntu Workflow *TEST*

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Version of Auto-GPT (branch or ref) to checkout. Default is v0.2.2'
        required: false
        default: 'v0.2.2'

jobs:
  build-and-test:
    name: Test on Cloud Runner with ${{ github.event.inputs.ref }}  # Dynamically name the job based on the Auto-GPT version being tested
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AutoGPT repository
        uses: actions/checkout@v2
        with:
          repository: Significant-Gravitas/Auto-GPT
          ref: ${{ github.event.inputs.ref }}
          path: autogpt
        
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Upgrade pip and install dependencies
      working-directory: autogpt
      run: |
        sudo apt-get update && sudo apt-get dist-upgrade
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@1.0.11

    - name: Ensure Docker is running
      run: |
        docker info

    - name: Configure .env file
      working-directory: autogpt
      run: |
        templateContent=$(cat .env.template)
        apiKeyReplacement=${templateContent/your-openai-api-key/${{ secrets.OPENAI_API_KEY }}}
        configContent=${apiKeyReplacement/EXECUTE_LOCAL_COMMANDS=False/EXECUTE_LOCAL_COMMANDS=True}
        echo "$configContent" > .env

    - name: Create auto-gpt.json file
      working-directory: autogpt
      run: |
        touch auto-gpt.json

    - name: Run PyTest to evaluate Auto-GPT coverage
      working-directory: autogpt
      run: |
        pytest --cov=autogpt

    - name: Run AutoGPT command
      working-directory: autogpt
      run: |
        inputSequence=(
          "CalculatorDev-GPT"
          "an AI designed to write a calculator app named 'calculator-gpt.py' in Python. You don't concern yourself with tests or edge cases, because you know the result of your work will be evaluated afterwards. Speed and efficiency are your utmost concerns, so you create scripts as quickly as possible without requiring user input"
          "Create a Python file called 'calculator-gpt.py' in the auto_gpt_workspace directory"
          "Create distinct addition, subtraction, multiplication, and division functions in 'calculator-gpt.py'. This Python script will be used to perform mathematical operations. Ensure that 'calculator-gpt.py' can be used in the terminal. Example usage: 'python calculator-gpt.py 5*6' example output: '30'. Example usage 2: 'python calculator-gpt.py 81/9' example 2 output: '9'"
          "Modify the script so when the result of a calculation is ever 42, instead of outputting the result, calculator-gpt.py will output only the text string 'The answer to life, the universe, and everything'"
          "Check 'calculator-gpt.py' for any redundancy and ensure it's clean, minimal, and readable"
          ""
          "y -15"
          "n"
        )
        printf '%s\n' "${inputSequence[@]}" | python -m autogpt --gpt3only
