name: Local calculator-gpt.py test

on:
  workflow_dispatch:

env:
  # https://github.com/tox-dev/tox/issues/1468
  python-version: '3.10'
  PY_COLORS: 1 # Enable colors for PyTest

jobs:
  build-and-test:
    name: Testing version ${{ github.event.inputs.ref }}  # Dynamically name the job based on the Auto-GPT version being tested
    runs-on: ubuntu-latest
    steps:
          
      - name: Check Python version
        run: python --version

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: AbstractMonkey/AutoGPT-Calculator-Benchmark
          path: autogpt-calculator-benchmark

      - name: Test calculator-gpt.py script
        working-directory: autogpt-calculator-benchmark
        run: |
          bash test_calculator_gpt.sh
