name: AutoGPT Workflow Test

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout AutoGPT repository
      uses: actions/checkout@v2
      with:
        repository: Significant-Gravitas/Auto-GPT
        ref: v0.2.2
        path: autogpt
        
    - name: Actions
      run: |
        find / -name "autogpt"
        
    - name: Checkout AutoGPT-Calculator-Benchmark repository
      uses: actions/checkout@v2
      with:
        repository: AbstractMonkey/AutoGPT-Calculator-Benchmark
        
    - name: Actions
      run: |
          cd ..
          ls -a
          cd ..
          ls -a
          cd ..
          ls -a
          
    - name: Actions
      run: |
          mkdir autogpt/auto_gpt_workspace
          cp ../autogpt-calculator-benchmark/calculator-gpt-tests.txt ../autogpt/auto_gpt_workspace/calculator-gpt-tests.txt
          cp ../autogpt-calculator-benchmark/test_calculator_gpt.sh ../autogpt/auto_gpt_workspace/test_calculator_gpt.sh
