name: AutoGPT Workflow Test

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout AutoGPT repository
      uses: actions/checkout@v2
      with:
        repository: Significant-Gravitas/Auto-GPT
        ref: v0.2.2
        path: autogpt
        
    - name: Checkout AutoGPT-Calculator-Benchmark repository
      uses: actions/checkout@v2
      with:
        repository: AbstractMonkey/AutoGPT-Calculator-Benchmark
          
    - name: Actions
      run: |
          mkdir autogpt/auto_gpt_workspace
          cp /home/runner/work/AutoGPT-Calculator-Benchmark/AutoGPT-Calculator-Benchmark/calculator-gpt-tests.txt /home/runner/work/AutoGPT-Calculator-Benchmark/AutoGPT-Calculator-Benchmark/autogpt/auto_gpt_workspace/calculator-gpt-tests.txt
          cp /home/runner/work/AutoGPT-Calculator-Benchmark/AutoGPT-Calculator-Benchmark/test_calculator_gpt.sh /home/runner/work/AutoGPT-Calculator-Benchmark/AutoGPT-Calculator-Benchmark/autogpt/auto_gpt_workspace/test_calculator_gpt.sh
          cd /home/runner/work/AutoGPT-Calculator-Benchmark/AutoGPT-Calculator-Benchmark/autogpt/auto_gpt_workspace/
          ls -a
